const animalEmojis = {
  Butterfly: "🦋",
  Crocodile: "🐊",
  Dolphin: "🐬",
  Eagle: "🦅",
  Dragon: "🐲",
  Elephant: "🐘",
  Bee: "🐝",
  Penguin: "🐧",
  Shark: "🦈",
  Bat: "🦇",
  Hedgehog: "🦔",
  Kangaroo: "🦘",
  Lion: "🦁",
  Peacock: "🦚",
  Parrot: "🦜",
  Spider: "🕷",
  Swan: "🦢",
  Tiger: "🐯",
  Turkey: "🦃",
  Owl: "🦉",
  Duck: "🦆",
  Flamingo: "🦩",
  Squid: "🦑",
  Monkey: "🐒",
  Pig: "🐖",
  Dog: "🐕",
  Fish: "🐟",
  Turtle: "🐢",
  Chipmunk: "🐿",
  Snake: "🐍",
  Frog: "🐸",
};

export default animalEmojis;
